using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Tests_278955818_Namespace
{
    [TestClass]
    class Tests_212301256_Class
    {
        [TestMethod]
        public void Test_FirstClass_Generate_Method()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void Test_FirstClass_GetGeneratingType_Method()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void Test_SecondClass_Calculate_Method()
        {
            Assert.Fail("autogenerated");
        }
    }
}