using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Tests_890743837_Namespace
{
    [TestClass]
    class Tests_791373691_Class
    {
        [TestMethod]
        public void Test_FirstClass_Generate_Method()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void Test_FirstClass_GetGeneratingType_Method()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void Test_SecondClass_Calculate_Method()
        {
            Assert.Fail("autogenerated");
        }
    }
}